config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }

  resources :cuties do
    resources :posts
  end

  root 'static_pages/users#index'

  resources :users, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :users
      resources :cuties
    end
  end

  namespace :admin do
    resources :users, only: [:index, :destroy, :edit, :update]
  end

  namespace :static_pages do
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuty.rb
class Cuty < ApplicationRecord

  mount_uploader :cutie_pic, CutiePicUploader

  has_many :friender_friends, foreign_key: :friendee_id, class_name: "Friendship"
  has_many :friendee_friends, foreign_key: :friender_id, class_name: "Friendship"

  has_many :frienders, through: :friender_friends, source: :friender
  has_many :friendees, through: :friendee_friends, source: :friendee

  belongs_to :user
  has_many :posts

  validates :name, presence: true
  validates :cutie_pic, presence: true

  def friendslist
    friends = []

    self.frienders.each do |friend|
      if !friends.include?(friend)
        friends << friend
      end
    end

    self.friendees.each do |friend|
      if !friends.include?(friend)
        friends << friend
      end
    end

    return friends
  end


end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: "follower_id", class_name: "User"
  belongs_to :followee, foreign_key: "followee_id", class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :friender, foreign_key: "friender_id", class_name: "Cuty"
  belongs_to :friendee, foreign_key: "friendee_id", class_name: "Cuty"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :cuty

  validates :body, presence: true
  validates :cuty_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cuties

  has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow"
  has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"
  has_many :followers, through: :follower_follows, source: :follower
  has_many :followees, through: :followee_follows, source: :followee

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true
  validates :email,
    format: { with: /\A.+@.+\..+\z/i }
  validates :encrypted_password,
    length: { minimum: 6 }
  validates :sign_in_count, presence: true,
    numericality: { greater_than_or_equal_to: 0, only_integer: true }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


 def admin?
   role == "admin"
 end
 
end

app/controllers/api/v1/cuties_controller.rb
class Api::V1::CutiesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show
    render json: Cuty.find(params[:id])
  end

  def destroy
    cutie = Cuty.find(params[:id])
    posts = cutie.posts
    if current_user == cutie.user
      cutie.destroy
      posts.destroy_all
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

  def show
    render json: User.find(params[:id])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :team_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :team_name])
  end

  def after_sign_in_path_for(*)
    if !user_signed_in?
      root_path
    else
      current_user
    end
  end

end

app/controllers/cuties_controller.rb
class CutiesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @cuties = Cuty.all.shuffle
  end

  def show
    @cutie = Cuty.find(params[:id])
    @user = @cutie.user
    @posts = @cutie.posts.order(created_at: :desc)
    @buddies = @cutie.friendslist
    @new_post = Post.new
  end

  def new
    @cutie = Cuty.new
  end

  def create
    @cutie = Cuty.new(cuty_params)
    @cutie.user = current_user
    if @cutie.save
      redirect_to @cutie, notice: "Cutie Successfully Added!"
    else
      flash[:notice] = @cutie.errors.full_messages.join(', ')
      render action: 'new'
    end

    @team = @cutie.user.cuties

    @team.each do |member|
      if member != @cutie
        Friendship.create(
          friender: member,
          friendee: @cutie
        )
      end
    end

  end

  def edit
    @cutie = Cuty.find(params[:id])
  end

  def update
    @cutie = Cuty.find(params[:id])
    if current_user == @cutie.user
      if @cutie.update(cuty_params)
        redirect_to @cutie, notice: "Cutie Successfully Updated!"
      else
        flash[:notice] = @cutie.errors.full_messages.join(', ')
        render action: 'edit'
      end
    else
      flash[:notice] = "Invalid user. You didn't create this!"
      render action: 'edit'
    end
  end

  def destroy
    @cutie = Cuty.find(params[:id])
    @cutie.destroy
    redirect_to user_path(current_user)
  end

  private

  def cuty_params
    params.require(:cuty).permit(:name, :bio, :cutie_type, :species, :birthdate, :cutie_pic, :wild, :favorite_genre, :location)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new

  end


  def create
    @new_post = Post.new(post_params)
    @cutie = Cuty.find(params[:cuty_id])
    @new_post.cuty = @cutie

    if @new_post.save
      redirect_to @cutie, notice: "Activity Submitted Successfully!"
    else
      flash[:notice] = @new_post.errors.full_messages.join(', ')
      redirect_to @cutie
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, :media_url, :link_url)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    protected

    def after_update_path_for(*)
      current_user
    end
end

app/controllers/static_pages.controller.rb
class StaticPagesController < ApplicationController
  def index
    
  end
end

app/controllers/static_pages/users_controller.rb
class StaticPages::UsersController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @cuties = @user.cuties
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuties/edit.html.erb
<div class="container text-center">
  <h1>Edit <%= @cutie.name %></h1>
  <div class="row">
    <%= form_for @cutie do |f| %>
      <div class="text-right five columns">
        <%= f.label :name %>
        <%= f.text_field :name %><br>

        <%= f.label :bio %>
        <%= f.text_field :bio %><br>

        <%= f.label :cutie_type, 'Cutie Type' %>
        <%= f.text_field :cutie_type %><br>

        <%= f.label :species %>
        <%= f.text_field :species %><br>

        <%= f.label :birthdate %>
        <%= f.date_select(:birthdate, start_year: Date.current.year, end_year: 1900, include_blank: true) %><br>

        <%= f.label :favorite_genre, "#{@cutie.name}'s favorite book genre" %>
        <%= f.collection_select(:favorite_genre, [
          # ["Art", "art"],
          # ["Biography", "biography"],
          # ["Business", "business"],
          # ["Chick-lit"],
          # ["Children's"],
          # ["Christian"],
          ["Classics", "classics"],
          # ["Comics"],
          # ["Contemporary"],
          # ["Cookbooks"],
          ["Crime", "crime"],
          # ["Ebooks"],
          ["Fantasy", "fantasy"],
          # ["Fiction"],
          ["Gay and Lesbian", "gay-and-lesbian"],
          ["Graphic Novels", "graphic-novels"],
          ["Historical Fiction", "historical-fiction"],
          ["History", "history"],
          ["Horror", "horror"],
          # ["Humor and Comedy"],
          # ["Manga"],
          # ["Memoir"],
          # ["Music"],
          ["Mystery", "mystery"],
          ["Non-fiction", "non-fiction"],
          # ["Paranormal"],
          # ["Philosophy"],
          # ["Poetry"],
          # ["Psychology"],
          # ["Religion"],
          ["Romance", "romance"],
          # ["Science"],
          ["Science Fiction", "science-fiction"],
          # ["Self help"],
          ["Suspense", "suspense"],
          # ["Spirituality"],
          # ["Sports"],
          ["Thriller", "thriller"],
          ["Travel", "travel"],
          ["Young-Adult", "young-adult"]
        ], :second, :first, {:include_blank  => 'choose genre' }) %><br>

        <!-- <%= f.label :location, "What zipcode does your cutie like to hang out in?" %>
        <%= f.text_field :location %><br> -->

      </div>

      <div class="text-left five columns">
        <%= f.label :cutie_pic, 'Cutie Pic' %>
        <%= f.file_field :cutie_pic %><br>
        <%= image_tag(@cutie.cutie_pic, class: "index-pic") %><br>

        <span>
          <%= f.check_box :wild %>
          <%= f.label :wild, "Check this box if you'd like " + @cutie.name + " to go on adventures and make new friends you can read about when you view their page."%>
          <p class="wild-explanation">When this box is checked a status update will be automatically posted by your cutie up to once a day. They may post a status, make a friend, or read a book from their favorite genre! When you visit their page, you can see what they've been up to while you weren't looking!</p>
        </span>

        <%= f.submit "Edit #{@cutie.name}" %>
      </div>
    <% end %>
  </div>
</div>

app/views/cuties/index.html.erb
<div class="" ontouchstart="this.classList.toggle("hover")">
  <h1>Meet The Cuties</h1>
  <% @cuties.each do |cutie| %>

    <%=link_to cuty_path(cutie) do %>

      <div class="">
        <div class="">
          <%= image_tag(cutie.cutie_pic, class: "") %><br>
        </div>

        <div class="">
          <%= image_tag(cutie.cutie_pic, class: "") %><br>
          <%= cutie.name %>
        </div>
      </div>

    <% end %>

  <% end %>

</div>

app/views/cuties/new.html.erb
<div class="container text-center">
  <div class="row">
    <h1>Add A Cutie</h1>
      <%= form_for @cutie do |f| %>
        <div class="text-right five columns">
          <%= f.label :name %>
          <%= f.text_field :name %><br>

          <%= f.label :bio %>
          <%= f.text_field :bio %><br>

          <%= f.label :cutie_type, 'Cutie Type' %>
          <%= f.text_field :cutie_type %><br>

          <%= f.label :species %>
          <%= f.text_field :species %><br>

          <%= f.label :birthdate %>
          <%= f.date_select(:birthdate, start_year: Date.current.year, end_year: 1900, include_blank: true) %><br>
        </div>

        <div class="text-left five columns">
          <%= f.label :cutie_pic, 'Cutie Pic' %>
          <%= f.file_field :cutie_pic %>
          <%= f.hidden_field :cutie_pic_cache %>
          <%= f.submit "Add Cutie" %>
        </div>
      <% end %>
    </div>



</div>

app/views/cuties/show.html.erb
<div class="container">

  <div class="row">
    <div class="photo-area five columns text-left">

      <% if @cutie.user == current_user %>
        <h2>Hi, <%= @cutie.name %></h2><br>
      <% else %>
        <h1>Meet <%= @cutie.name %></h1><br>
      <% end %>

      <%= image_tag(@cutie.cutie_pic, class: "show-pic") %>
        <div class="text-left">

          <% if @cutie.user == current_user %>
            What have you been up to?<br>
            <%= form_for([@cutie, @new_post]) do |f| %>
              <%= f.text_area :body, size: "69x2" %><br>
              <%= f.submit "Update Status" %>
            <% end %>
          <% end %>

          <% if @cutie.bio != "" %>
            Bio: <%= @cutie.bio  %><br>
          <% end %>

          <% if @cutie.cutie_type != "" %>
            Type: <%= @cutie.cutie_type  %><br>
          <% end %>

          <% if @cutie.species != "" %>
            Species: <%= @cutie.species  %><br>
          <% end %>

          <% if @cutie.birthdate %>
            Birth Date: <%= @cutie.birthdate.strftime('%B %d, %Y')  %><br>
          <% end %>

          <% if @cutie.favorite_genre %>
            Favorite Book Genre: <%= @cutie.favorite_genre %><br>
          <% end %>

        </div>
    </div>

    <div class="seven columns">
        <div class="buddies">
          <h3>Buds!</h3>
          <% @buddies.each do |buddy| %>
            <%= link_to cuty_path(buddy) do %>
              <%= image_tag(buddy.cutie_pic, class: "buddy-pic") %>
            <% end %>
          <% end %>
        </div>
        <div class="activity">
        Recent Activity:
        <% @posts.each do |post| %>
          <li>
            <%= post.created_at.strftime('%m/%d/%Y - %I:%M:%S %p') %><br>


              <% if post.media_url %>
                <a href="<%= post.link_url %>">
                  <img src="<%= post.media_url %>" class="post-media">
                </a>
              <% end %>

            <%= post.body %>
          </li>
        <% end %>
      </div>
    </div>

  </div>
  <div class="row">


  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Cutie Space</title>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower|Lora|Merriweather|Mukta|Poppins" rel="stylesheet">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="row">
      <span class="three columns">
        <span class="logo">
          <%= link_to cuties_path do %>
            <%=  image_tag("logo.png")  %>
          <% end %>
        </span>
      </span>

      <div class="nav-link-box nine columns">

        <% if user_signed_in? %>
          <%= link_to user_path(current_user) do %>
            <span class="nav-links">Signed in as <%= current_user.username %></span>
          <% end %>
          <span class="nav-links"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></span>
        <% else %>
          <span class="hidden nav-links">CutieSpace</span>
          <span class="nav-links"><%= link_to 'Sign In', new_user_session_path %></span>
          <span class="nav-links"><%= link_to 'Sign Up', new_user_registration_path %></span>
        <% end %>

        <span class="nav-links"><%= link_to 'See Everyone', cuties_path %></span>
      </div>
    </nav>

    <span class="alerts">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </span>

    <%= yield %>

    <div class="footer">
      CutieSpace was created by <a href="https://www.linkedin.com/in/alfair/">Al Fair</a>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/crew_edit.html.erb
testing crew edit page

app/views/static_pages/index.html.erb
<h1>Splash page</h1>

app/views/static_pages/users/index.html.erb
<h1>Testing 123</h1>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, user_path(user)%><br>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div id="app">
</div>

app/views/users/xshow.html.erb
<div class="container">

  <div class="row team-header">
    <div class="two columns">
      Hi, <%= @user.username %>!<br>
      <%= link_to "Edit Your Profile", edit_registration_path(current_user) %>
    </div>
  </div>

  <ul>
    <% if @user.team_name %>
      <h2><%= @user.team_name %></h2>
    <% else %>
      <h2><%= @user.username %>'s Crew</h2>
    <% end %>

    <% @cuties.each do |cutie| %>
      <li class="crew-box row">
        <span class="two columns">
          <%= image_tag(cutie.cutie_pic, class: "crew-pic") %><br>
        </span>

        <span class="three columns">
          <%= button_to "Visit #{cutie.name}", cuty_path(cutie), method: :get %>
        </span>

        <span class="three columns">
          <%= button_to "Edit #{cutie.name}", edit_cuty_path(cutie), method: :get %>
        </span>
        <span class="three columns">
          <%= button_to "Delete #{cutie.name}", cutie, data: { confirm: "Are you sure?" }, method: :delete %>
        </span>
      </li>
    <% end %>
    <li class="crew-box row">
      <span class="two columns">
        <%= image_tag("placeholder.jpg", class: "crew-pic") %><br>
      </span>

      <span class="three columns">
        Add A Cutie<br>
        Add A Cutie
      </span>

      <span class="three columns">
        Add A Cutie
      </span>
      <span class="three columns">
        <%= button_to "Add A Cutie", new_cuty_path, method: :get %>
      </span>
    </li>


  </ul>

</div>